-- CasaStock V0.1. Run with `supabase db push` after linking a project.
create extension if not exists pgcrypto;
create type public.member_role as enum ('owner','member');
create type public.movement_kind as enum ('purchase','consumption','adjustment');
create type public.casacoin_transaction_kind as enum ('earn','spend','adjustment');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, created_at timestamptz not null default now());
create table public.households (id uuid primary key default gen_random_uuid(), name text not null check (char_length(name) between 1 and 80), created_by uuid not null references auth.users(id), created_at timestamptz not null default now());
create table public.household_members (household_id uuid not null references public.households(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role public.member_role not null default 'member', created_at timestamptz not null default now(), primary key(household_id,user_id));
create table public.product_catalog (id uuid primary key default gen_random_uuid(), name text not null, brand text, barcode text unique, category text, default_unit text not null default 'un', created_at timestamptz not null default now());
create table public.household_products (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, catalog_product_id uuid references public.product_catalog(id), name text not null, brand text, category text, barcode text, unit text not null default 'un', minimum_quantity numeric(12,2) not null default 0 check(minimum_quantity>=0), ideal_quantity numeric(12,2), current_quantity numeric(12,2) not null default 0 check(current_quantity>=0), created_at timestamptz not null default now());
create table public.markets (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, name text not null, created_at timestamptz not null default now(), unique(household_id,name));
create table public.purchases (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, market_id uuid references public.markets(id), purchased_on date not null, total_amount numeric(12,2) not null check(total_amount>=0), created_by uuid not null references auth.users(id), created_at timestamptz not null default now());
create table public.purchase_items (id uuid primary key default gen_random_uuid(), purchase_id uuid not null references public.purchases(id) on delete cascade, household_product_id uuid not null references public.household_products(id), quantity numeric(12,2) not null check(quantity>0), unit_price numeric(12,2) not null check(unit_price>=0), total_amount numeric(12,2) not null check(total_amount>=0));
create table public.stock_movements (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, household_product_id uuid not null references public.household_products(id), kind public.movement_kind not null, quantity_delta numeric(12,2) not null check(quantity_delta<>0), occurred_on date not null, purchase_item_id uuid references public.purchase_items(id), created_by uuid not null references auth.users(id), created_at timestamptz not null default now());
create table public.price_records (id uuid primary key default gen_random_uuid(), catalog_product_id uuid references public.product_catalog(id), household_product_id uuid not null references public.household_products(id) on delete cascade, market_id uuid references public.markets(id), observed_on date not null, unit_price numeric(12,2) not null, created_by uuid not null references auth.users(id), created_at timestamptz not null default now());
create table public.shopping_lists (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, name text not null default 'Lista de compras', created_at timestamptz not null default now());
create table public.shopping_list_items (id uuid primary key default gen_random_uuid(), shopping_list_id uuid not null references public.shopping_lists(id) on delete cascade, household_product_id uuid references public.household_products(id) on delete set null, suggested_quantity numeric(12,2), checked boolean not null default false, created_at timestamptz not null default now());
create table public.casacoin_wallets (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, balance numeric(14,2) not null default 0, created_at timestamptz not null default now());
create table public.casacoin_transactions (id uuid primary key default gen_random_uuid(), wallet_id uuid not null references public.casacoin_wallets(id) on delete cascade, kind public.casacoin_transaction_kind not null, amount numeric(14,2) not null check(amount<>0), description text, created_at timestamptz not null default now());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id) values(new.id); insert into public.casacoin_wallets(user_id) values(new.id); return new; end;$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_household_member(p_household uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.household_members where household_id=p_household and user_id=(select auth.uid()))$$;
create or replace function public.create_household(household_name text) returns uuid language plpgsql security definer set search_path=public as $$declare h uuid; begin if auth.uid() is null then raise exception 'not authenticated'; end if trim(household_name)='' then raise exception 'household name is required'; end if; insert into public.households(name,created_by) values(trim(household_name),auth.uid()) returning id into h; insert into public.household_members(household_id,user_id,role) values(h,auth.uid(),'owner'); return h; end;$$;
create or replace function public.record_purchase(p_household_id uuid,p_product_id uuid,p_market_name text,p_quantity numeric,p_unit_price numeric,p_purchased_on date) returns uuid language plpgsql security definer set search_path=public as $$declare m uuid; p uuid; pi uuid; begin if auth.uid() is null or not public.is_household_member(p_household_id) then raise exception 'not allowed'; end if; if p_quantity<=0 or p_unit_price<0 then raise exception 'invalid amount'; end if; if not exists(select 1 from public.household_products where id=p_product_id and household_id=p_household_id) then raise exception 'product not in household'; end if; insert into public.markets(household_id,name) values(p_household_id,trim(p_market_name)) on conflict(household_id,name) do update set name=excluded.name returning id into m; insert into public.purchases(household_id,market_id,purchased_on,total_amount,created_by) values(p_household_id,m,p_purchased_on,round(p_quantity*p_unit_price,2),auth.uid()) returning id into p; insert into public.purchase_items(purchase_id,household_product_id,quantity,unit_price,total_amount) values(p,p_product_id,p_quantity,p_unit_price,round(p_quantity*p_unit_price,2)) returning id into pi; update public.household_products set current_quantity=current_quantity+p_quantity where id=p_product_id; insert into public.stock_movements(household_id,household_product_id,kind,quantity_delta,occurred_on,purchase_item_id,created_by) values(p_household_id,p_product_id,'purchase',p_quantity,p_purchased_on,pi,auth.uid()); insert into public.price_records(household_product_id,market_id,observed_on,unit_price,created_by) values(p_product_id,m,p_purchased_on,p_unit_price,auth.uid()); return p; end;$$;
create or replace function public.consume_stock(p_household_id uuid,p_product_id uuid,p_quantity numeric,p_occurred_on date) returns void language plpgsql security definer set search_path=public as $$begin if auth.uid() is null or not public.is_household_member(p_household_id) then raise exception 'not allowed'; end if; update public.household_products set current_quantity=current_quantity-p_quantity where id=p_product_id and household_id=p_household_id and current_quantity>=p_quantity; if not found then raise exception 'insufficient stock'; end if; insert into public.stock_movements(household_id,household_product_id,kind,quantity_delta,occurred_on,created_by) values(p_household_id,p_product_id,'consumption',-p_quantity,p_occurred_on,auth.uid()); end;$$;

alter table public.profiles enable row level security; alter table public.households enable row level security; alter table public.household_members enable row level security; alter table public.product_catalog enable row level security; alter table public.household_products enable row level security; alter table public.markets enable row level security; alter table public.purchases enable row level security; alter table public.purchase_items enable row level security; alter table public.stock_movements enable row level security; alter table public.price_records enable row level security; alter table public.shopping_lists enable row level security; alter table public.shopping_list_items enable row level security; alter table public.casacoin_wallets enable row level security; alter table public.casacoin_transactions enable row level security;
grant select,insert,update,delete on all tables in schema public to authenticated; revoke all on function public.handle_new_user(),public.is_household_member(uuid),public.create_household(text),public.record_purchase(uuid,uuid,text,numeric,numeric,date),public.consume_stock(uuid,uuid,numeric,date) from public; grant execute on function public.is_household_member(uuid),public.create_household(text),public.record_purchase(uuid,uuid,text,numeric,numeric,date),public.consume_stock(uuid,uuid,numeric,date) to authenticated;
create policy "profile own" on public.profiles for all to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy "households members read" on public.households for select to authenticated using(public.is_household_member(id));
create policy "members household access" on public.household_members for select to authenticated using(public.is_household_member(household_id));
create policy "catalog readable" on public.product_catalog for select to authenticated using(true);
create policy "household products access" on public.household_products for all to authenticated using(public.is_household_member(household_id)) with check(public.is_household_member(household_id));
create policy "markets access" on public.markets for all to authenticated using(public.is_household_member(household_id)) with check(public.is_household_member(household_id));
create policy "purchases access" on public.purchases for select to authenticated using(public.is_household_member(household_id));
create policy "purchase items access" on public.purchase_items for select to authenticated using(exists(select 1 from public.purchases p where p.id=purchase_id and public.is_household_member(p.household_id)));
create policy "movements access" on public.stock_movements for select to authenticated using(public.is_household_member(household_id));
create policy "prices access" on public.price_records for select to authenticated using(exists(select 1 from public.household_products hp where hp.id=household_product_id and public.is_household_member(hp.household_id)));
create policy "lists access" on public.shopping_lists for all to authenticated using(public.is_household_member(household_id)) with check(public.is_household_member(household_id));
create policy "list items access" on public.shopping_list_items for all to authenticated using(exists(select 1 from public.shopping_lists l where l.id=shopping_list_id and public.is_household_member(l.household_id))) with check(exists(select 1 from public.shopping_lists l where l.id=shopping_list_id and public.is_household_member(l.household_id)));
create policy "wallet own" on public.casacoin_wallets for select to authenticated using(user_id=(select auth.uid()));
create policy "transactions own" on public.casacoin_transactions for select to authenticated using(exists(select 1 from public.casacoin_wallets w where w.id=wallet_id and w.user_id=(select auth.uid())));
create index household_products_household_idx on public.household_products(household_id); create index purchases_household_date_idx on public.purchases(household_id,purchased_on); create index stock_movements_product_idx on public.stock_movements(household_product_id,occurred_on);
